config/routes.rb
Rails.application.routes.draw do

devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admin do
    resources :users
    get 'search_tag'=>'posts#search_tag'
    get 'search_favorite' => 'posts#search_favorite'
    resources :posts do
      resources :post_comments, only: [:destroy]
    end
  end

  get '/search', to: 'searches#search'
  scope module: :public do
    root to: 'homes#top'
    devise_for :users, controllers: {
      registrations: 'public/users/registrations',
      sessions: 'public/users/sessions'

    }
    resources :users do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    get 'search_favorite' => 'posts#search_favorite'
    get 'search_tag'=>'posts#search_tag'
    get 'search' => 'posts#search'
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
    delete 'notification/destroy_all' => 'notifications#destroy_all'

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

  belongs_to :user
  attachment :image
  has_many :post_comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :notifications, dependent: :destroy

  has_many :post_tags,dependent: :destroy
  has_many :tags,through: :post_tags

  #いいね
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  #通知
  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      post_id: id,
      visited_id: user_id,
      action: "favorite"
      )
    notification.save
  end

  def create_notification_comment!(current_user,post_comment_id)
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, post_comment_id, visited_id)
    notification = current_user.active_notifications.new(
    post_id: id,
    post_comment_id: post_comment_id,
    visited_id: visited_id,
    action: 'comment')
    if notification.visitor_id == notification.visited_id
      notification.checked == true
    end
    notification.save
  end

  #タグ
  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

     old_tags.each do |old|
      tag_id = Tag.find_by(name: old).id
      self.post_tags.find_by(tag_id: tag_id).destroy
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
   end
  end

  #検索
  def self.search(keyword)
    where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"])
  end

  def self.last_week
    Post.find(Favorite.group(:post_id).where(created_at: Time.current.all_week).order('count(post_id) desc').limit(12).pluck(:post_id))
  end


end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @posts = Post.page(params[:page]).per(12).reverse_order
    @tag_list=Tag.all
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @post_tags = @post.tags
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end

  def search_tag
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @posts = @tag.posts.page(params[:page]).per(12)
  end

  def search_favorite
    @posts = Post.last_week
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_index.html.erb
<div class="row justify-content-start">
  <% posts.each do |post| %>
  <div class="col-12 col-md-6 col-lg-3">
    <div class="card-deck p-3">
      <div class="card content-card border-dark">
        <div class="card-header p-0">
          <div class="card-img-top">
            <%= link_to admin_post_path(post.id) do %>
              <%= attachment_image_tag post, :image, fallback:'no_image.png' %>
            <% end %>
          </div>
        </div>
        <div class="card-body">
          <div class="title_box">
            <h5 class="card-title">
              <%= link_to admin_post_path(post.id), class:'text-reset' do %>
                <%= post.title %>
              <% end %>
            </h5>
          </div>
          <p>
            <%=link_to admin_user_path(post.user), class:'btn btn-secondary' do %>
              <%= post.user.name %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="texts-wrapper">
    <div class="row subtitle_box">
      <div class="col-3"></div>
      <div class="col-6">
        <h1 class="subtitle text-center">投稿一覧</h1>
      </div>
      <div class="col-3 search-form pt-3">
        <%= form_tag(search_path, method: :get) do %>
          <%= text_field_tag 'content' %></br>
          <%= select_tag 'model', options_for_select({ "User" => "user", "Post" => "post" }) %>
          <%= select_tag 'method', options_for_select({ "完全一致" => "perfect", "部分一致" => "partial", "前方一致" => "forward_match", "後方一致" => "backward_match" }) %>
          <%= submit_tag '検索' %>
        <% end %>
        <div>
          <%= link_to "人気投稿を見る", admin_search_favorite_path, class:'btn btn-primary' %>
        </div>
      </div>
    </div>
    <%= render 'index', posts: @posts%>
    <div class="row">
      <div class="col-5"></div>
      <div class="col-2">
         <%= paginate @posts %>
      </div>
      <div class="col-5"></div>
    </div>
  </div>
</div>

app/views/admin/posts/search_favorite.html.erb
<div class="container">
  <div class="texts-wrapper">
    <div class="row subtitle_box">
      <div class="col-3"></div>
      <div class="col-6">
        <h1 class="subtitle text-center">今週の人気投稿</h1>
      </div>
      <div class="col-3"></div>
    </div>
    <%= render 'index', posts: @posts %>
  </div>
</div>

app/views/admin/posts/search_tag.html.erb
<div class="texts-wrapper">
  <div class="container">
    <div class="contents-title text-center">
      <h1>タグが<span class="border-bottom border-dark"><%=@tag.name%></span>の投稿一覧</h1>
    </div>
    <%= render 'index', posts: @posts %>
  </div>
  <div class="row">
    <div class="col-5"></div>
    <div class="col-2">
       <%= paginate @posts %>
    </div>
    <div class="col-5"></div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row border-bottom border-5 pt-3">
    <div class="col-9 ">
      <div class="subtitle d-flex">
        <h2 class="post_title text-center mb-0">
          <%= @post.title %>
        </h2>
        <%= link_to "削除する", admin_post_path(@post), method: :delete, class: 'btn btn-danger', data: {confirm: "[確認]投稿を削除しますか？"} %>
      </div>
      <div class="user_name text-start mt-0">
        <%= @post.user.name %>
      </div>
      <div>
        <% @post_tags.each do |tag| %>
          <i class="fas fa-tag">
            <%= link_to tag.name, admin_search_tag_path(tag_id: tag.id)%>
          </i>
        <% end %>
      </div>
      <div>
        <%= @post.body %>
      </div>
    </div>
    <div class="col-3">
      <div class="profile_image p-0">
        <%= attachment_image_tag @post, :image, fallback: 'no_image.png', size:'300x300' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-8">
      <div class="comments">
        <%= render 'admin/post_comments/index', post: @post %>
      </div>
    </div>
    <div class="col-4"></div>
  </div>
</div>