config/routes.rb
Rails.application.routes.draw do

devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admin do
    resources :users
    get 'search_tag'=>'posts#search_tag'
    get 'search_favorite' => 'posts#search_favorite'
    resources :posts do
      resources :post_comments, only: [:destroy]
    end
  end

  get '/search', to: 'searches#search'
  scope module: :public do
    root to: 'homes#top'
    devise_for :users, controllers: {
      registrations: 'public/users/registrations',
      sessions: 'public/users/sessions'

    }
    resources :users do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    get 'search_favorite' => 'posts#search_favorite'
    get 'search_tag'=>'posts#search_tag'
    get 'search' => 'posts#search'
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
    delete 'notification/destroy_all' => 'notifications#destroy_all'

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :notifications, dependent: :destroy
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController

  before_action :authenticate_admin!

  def destroy
     PostComment.find_by(id:params[:id]).destroy
     @post = Post.find(params[:post_id])
     render :index
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/_index.html.erb
<% post.post_comments.each do |post_comment| %>
  <div>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %>
    <h5>
      <%= link_to admin_user_path(post_comment.user) do %>
        <%= post_comment.user.name %>
      <% end %>
    </h5>
  </div>
  <div class="comment text-break border-bottom border-dark">
    <%= post_comment.comment %>
    <%= link_to "削除する", admin_post_post_comment_path(post_comment.post,post_comment), method: :delete,class:'btn btn-sm btn-danger', data: { confirm: "【確認】コメントを削除しますか？" }, remote: true %>
  </div>
<% end %>

app/views/admin/post_comments/index.js.erb
$(".comments").html("<%= j(render 'index', { post: @post }) %>");
$("#post_comment_comment").val("");