config/routes.rb
Rails.application.routes.draw do

devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admin do
    resources :users
    get 'search_tag'=>'posts#search_tag'
    get 'search_favorite' => 'posts#search_favorite'
    resources :posts do
      resources :post_comments, only: [:destroy]
    end
  end

  get '/search', to: 'searches#search'
  scope module: :public do
    root to: 'homes#top'
    devise_for :users, controllers: {
      registrations: 'public/users/registrations',
      sessions: 'public/users/sessions'

    }
    resources :users do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    get 'search_favorite' => 'posts#search_favorite'
    get 'search_tag'=>'posts#search_tag'
    get 'search' => 'posts#search'
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
    delete 'notification/destroy_all' => 'notifications#destroy_all'

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error.html.erb
<% if model.errors.any? %>
  <%= model.errors.count %>件のエラーが発生しました
  <% model.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimalBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="bg-warning shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <% if user_signed_in? %>
          <div class="profile_image text-start">
            <% if unchecked_notifications.any? %>
              <i class="fa fa-circle" style="color: red;"></i>
            <% end %>
            <%= link_to user_path(current_user) do %>
              <%= attachment_image_tag current_user, :profile_image, :fill,100,100, fallback: 'no_image.png', size:'50x50', class:'rounded-circle' %>
            <% end %>
          </div>
        <% end %>
        <div class="container">
          <h1 class="main_title">animal_blog</h1>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-expanded="false" aria-controls="navbarNabDropdown" aria-labrl="Toggle nabigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item pr-3">
                  <%= link_to new_post_path, class:'text-reset' do %>
                    <i class="fas fa-paper-plane">新規投稿</i>
                  <% end %>
                </li>
                <li class="nav-item pr-3">
                  <%= link_to posts_path, class:'text-reset' do %>
                    <i class="fas fa-home">ホーム</i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class:'text-reset' do %>
                    <i class="fas fa-sign-in-alt">ログアウト</i>
                  <% end %>
                </li>
              <% elsif admin_signed_in? %>
                <li class="nav-item pr-3">
                  <%= link_to admin_posts_path, class:'text-reset' do %>
                    <i class="fas fa-home">ホーム</i>
                  <% end %>
                </li>
                <li class="nav-item pr-3">
                  <%= link_to admin_users_path, class:'text-reset' do %>
                    <i class="fas fa-user-circle">ユーザー</i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_admin_session_path, method: :delete, class:'text-reset' do %>
                    <i class="fas fa-sign-in-alt">ログアウト</i>
                  <% end %>
                </li>
              <% else %>
                  <li class="nav-item pr-3">
                  <%= link_to  new_user_registration_path, class:'text-reset' do %>
                    <i class="fas fa-user-plus">新規登録</i>
                  <% end %>
                </li>
                <li class="nav-item pr-3">
                  <%= link_to new_user_session_path, class:'text-reset' do %>
                    <i class="fas fa-sign-in-alt">サインイン</i>
                  <% end %>
                </li>
                <li class="nav-item text-right">
                  <%= link_to "管理者", new_admin_session_path, class:'text-reset' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
  </body>
</html>